# build step
FROM node:16.13.2-alpine as build
WORKDIR /app
COPY package.json ./
RUN npm install
COPY . ./
RUN npm run build

# environment variables
ENV REACT_APP_RAPID_API_FOOD_HOST=
ENV REACT_APP_RAPID_API_EXERCISE_HOST=
ENV REACT_APP_RAPID_API_EXERCISE_HOST_2=
ENV REACT_APP_RAPID_API_CALORIES_BURNED=
ENV REACT_APP_RAPID_API_MUSCLE_GROUP_IMAGE=
ENV REACT_APP_RAPID_API_KEY=
ENV REACT_APP_SUPABASE_KEY=
ENV REACT_APP_SUPABASE_URL=
ENV REACT_APP_NUTRITIONIX_KEY=
ENV REACT_APP_NUTRITIONIX_HOST=
ENV REACT_APP_NUTRITIONIX_APP_ID=


# release step
FROM nginx:1.21.5-alpine as release
COPY --from=build /app/build /usr/share/nginx/html/
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]